### ISSUE TITLE
Only downloads an empty file

### ISSUE THREAD

**Issue by Mela** [ozh/yourls-geoip-update#9]
When the plugin is run, it only downloads an empty GeoLite2-Country.tar.gz file. 

Regards,
Mela

**Comment by cocochepeau** [comment]
```
Fatal error: Uncaught UnexpectedValueException: internal corruption of phar "/var/www/html/user/plugins/yourls-geoip-update-master/GeoLite2-Country.tar.gz" (truncated entry) in /var/www/html/user/plugins/yourls-geoip-update-master/vendor/tronovav/geoip2-update/src/Client.php:316 Stack trace: #0 /var/www/html/user/plugins/yourls-geoip-update-master/vendor/tronovav/geoip2-update/src/Client.php(316): PharData->__construct('/var/www/html/u...') #1 /var/www/html/user/plugins/yourls-geoip-update-master/vendor/tronovav/geoip2-update/src/Client.php(186): tronovav\GeoIP2Update\Client->extract('GeoLite2-Countr...') #2 /var/www/html/user/plugins/yourls-geoip-update-master/vendor/tronovav/geoip2-update/src/Client.php(113): tronovav\GeoIP2Update\Client->updateEdition('GeoLite2-Countr...') #3 /var/www/html/user/plugins/yourls-geoip-update-master/run.php(26): tronovav\GeoIP2Update\Client->run() #4 /var/www/html/user/plugins/yourls-geoip-update-master/plugin.php(80): ozh_yourls_geoip2_update_client_run('ZyMb9V_AjzjZZco...') #5 /var/www/html/user/plugins/yourls-geoip-update-master/plugin.php(46): ozh_yourls_geoupd_update_db() #6 /var/www/html/includes/functions-plugins.php(803): ozh_yourls_geoupd_do_page() #7 /var/www/html/admin/plugins.php(8): yourls_plugin_admin_page('geoipupdate') #8 {main} thrown in /var/www/html/user/plugins/yourls-geoip-update-master/vendor/tronovav/geoip2-update/src/Client.php on line 316
```
